# permissions for end users to view attainablenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attainablenode-viewer-role
rules:
- apiGroups:
  - k8s-wol.github.com
  resources:
  - attainablenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-wol.github.com
  resources:
  - attainablenodes/status
  verbs:
  - get
