# permissions for end users to edit attainablenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attainablenode-editor-role
rules:
- apiGroups:
  - k8s-wol.github.com
  resources:
  - attainablenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-wol.github.com
  resources:
  - attainablenodes/status
  verbs:
  - get
