# permissions for end users to edit wakenodeuprequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wakenodeuprequest-editor-role
rules:
- apiGroups:
  - k8s-wol.github.com
  resources:
  - wakenodeuprequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-wol.github.com
  resources:
  - wakenodeuprequests/status
  verbs:
  - get
