# permissions for end users to view wakenodeuprequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wakenodeuprequest-viewer-role
rules:
- apiGroups:
  - k8s-wol.github.com
  resources:
  - wakenodeuprequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-wol.github.com
  resources:
  - wakenodeuprequests/status
  verbs:
  - get
