# permissions for end users to edit wolnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wolnode-editor-role
rules:
- apiGroups:
  - k8s-wol.github.com
  resources:
  - wolnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-wol.github.com
  resources:
  - wolnodes/status
  verbs:
  - get
